export const SET_USER = 'SET_USER';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_OUT = 'SIGN_OUT';


// Products action types
export const LOAD_STATE_PRODUCT = 'LOAD_STATE_PRODUCT';
export const LOAD_STATE_PRODUCT_COLLECTION = 'LOAD_STATE_PRODUCT_COLLECTION';
export const LOAD_STATE_PRODUCT_COLLECTION_ITEM = 'LOAD_STATE_PRODUCT_COLLECTION_ITEM';