export const SET_USER = 'SET_USER';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_OUT = 'SIGN_OUT';


// Products action types
export const LOAD_STATE_PRODUCT = 'LOAD_STATE_PRODUCT';
export const LOAD_STATE_PRODUCT_COLLECTION = 'LOAD_STATE_PRODUCT_COLLECTION';
export const LOAD_STATE_PRODUCT_COLLECTION_ITEM = 'LOAD_STATE_PRODUCT_COLLECTION_ITEM';

// Cart action types
 export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
 export const ADD_ID_TO_CART = 'ADD_ID_TO_CART '
 export const MINUS_PRODUCT = 'MINUS_PRODUCT';  
 export const PLUS_PRODUCT = 'PLUS_PRODUCT';
 export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';